name: Build and Push Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/apt-repo-server:${{ github.sha }}:lastest

      - name: Set Labels for Container Image
        run: |
          docker build . --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
                         --label "org.opencontainers.image.description=Automated APT Repository Server" \
                         --label "org.opencontainers.image.licenses=MIT"
